"""
Auto-generated endpoint constants.

Plugin: snf-instance-rest
Endpoints: 219
DO NOT EDIT — regenerate with: python -m post_it generate
"""

from post_it.models import Endpoint

Nodes = Endpoint(path="/redfish/v1/SFM/1/Nodes", methods=("GET", "POST", "PUT", "DELETE",))
FabricManagement = Endpoint(path="/redfish/v1/SFM/1/FabricManagement", methods=("GET", "PUT",))
InstanceManagement = Endpoint(path="/redfish/v1/SFM/1/InstanceManagement", methods=("GET", "PUT",))
NodeManagement = Endpoint(path="/redfish/v1/SFM/1/NodeManagement", methods=("GET", "PUT",))
NodesInterfaces = Endpoint(path="/redfish/v1/SFM/1/Nodes/Interfaces", methods=("GET",))
NodesConnectivityDetails = Endpoint(path="/redfish/v1/SFM/1/Nodes/ConnectivityDetails", methods=("GET",))
Interfaces = Endpoint(path="/redfish/v1/SFM/1/Interfaces", methods=("GET", "POST", "PUT", "DELETE",))
BlueprintTemplates = Endpoint(path="/redfish/v1/SFM/1/BlueprintTemplates", methods=("GET", "POST", "DELETE",))
BlueprintTemplatesImport = Endpoint(path="/redfish/v1/SFM/1/BlueprintTemplates/Import", methods=("POST",))
BlueprintTemplatesExport = Endpoint(path="/redfish/v1/SFM/1/BlueprintTemplates/Export", methods=("POST",))
BlueprintTemplatesTemplateJsonPayload = Endpoint(path="/redfish/v1/SFM/1/BlueprintTemplates/TemplateJsonPayload", methods=("GET",))
BlueprintTemplatesSpecJsonPayload = Endpoint(path="/redfish/v1/SFM/1/BlueprintTemplates/SpecJsonPayload", methods=("GET", "POST",))
V2_BlueprintTemplatesTemplateJsonPayload = Endpoint(path="/redfish/v2/SNF/BlueprintTemplates/TemplateJsonPayload", methods=("GET",))
V2_BlueprintTemplatesSpecJsonPayload = Endpoint(path="/redfish/v2/SNF/BlueprintTemplates/SpecJsonPayload", methods=("GET",))
TopologyGraph = Endpoint(path="/redfish/v1/SFM/1/TopologyGraph", methods=("GET",))
LLDPNeighbors = Endpoint(path="/redfish/v1/SFM/1/LLDPNeighbors", methods=("GET",))
Fabrics = Endpoint(path="/redfish/v1/SFM/1/Fabrics", methods=("GET", "POST", "PUT", "DELETE",))
FabricTemplateDefaults = Endpoint(path="/redfish/v1/SFM/1/FabricTemplateDefaults", methods=("GET", "POST", "PUT", "DELETE",))
HealthMonitor = Endpoint(path="/redfish/v1/SFM/1/HealthMonitor", methods=("GET",))
NodesFactoryReset = Endpoint(path="/redfish/v1/SFM/1/Nodes/FactoryReset", methods=("POST",))
NodesReboot = Endpoint(path="/redfish/v1/SFM/1/Nodes/Reboot", methods=("POST",))
NodesOwnership = Endpoint(path="/redfish/v1/SFM/1/Nodes/Ownership", methods=("POST",))
NodesTransceivers = Endpoint(path="/redfish/v1/SFM/1/Nodes/Transceivers", methods=("GET",))
NodesLocatorLed = Endpoint(path="/redfish/v1/SFM/1/Nodes/LocatorLed", methods=("POST",))
VlanTable = Endpoint(path="/redfish/v1/SFM/1/VlanTable", methods=("GET",))
FabricsNodesAdd = Endpoint(path="/redfish/v1/SFM/1/Fabrics/NodesAdd", methods=("POST", "PUT", "DELETE",))
FabricsNodesDelete = Endpoint(path="/redfish/v1/SFM/1/Fabrics/NodesDelete", methods=("POST", "PUT", "DELETE",))
LicenseGlobal = Endpoint(path="/redfish/v1/SFM/1/LicenseGlobal", methods=("GET", "POST", "PUT", "DELETE",))
LicenseInstall = Endpoint(path="/redfish/v1/SFM/1/LicenseInstall", methods=("GET", "POST", "PUT", "DELETE",))
LicenseHistory = Endpoint(path="/redfish/v1/SFM/1/License/History", methods=("GET", "POST", "PUT", "DELETE",))
LicenseRTU = Endpoint(path="/redfish/v1/SFM/1/License/RTU", methods=("GET", "POST", "PUT", "DELETE",))
LicenseRTM = Endpoint(path="/redfish/v1/SFM/1/License/RTM", methods=("GET", "POST", "PUT", "DELETE",))
SosReports = Endpoint(path="/redfish/v1/SFM/1/SosReports", methods=("GET", "POST", "PUT", "DELETE",))
SwitchSosReports = Endpoint(path="/redfish/v1/SFM/1/SwitchSosReports", methods=("GET", "POST", "PUT", "DELETE",))
ServiceDebug = Endpoint(path="/redfish/v1/SFM/1/ServiceDebug", methods=("GET", "POST", "PUT", "DELETE",))
ServiceDebugServiceNameInstanceNameServiceType = Endpoint(path="/redfish/v1/SFM/1/ServiceDebug/ServiceName/InstanceName/ServiceType", methods=("GET", "POST", "PUT", "DELETE",))
ServiceDebugServiceNameInstanceNameServiceTypeServiceDbgAttr = Endpoint(path="/redfish/v1/SFM/1/ServiceDebug/ServiceName/InstanceName/ServiceType/ServiceDbgAttr", methods=("GET", "POST", "PUT", "DELETE",))
Uplinks = Endpoint(path="/redfish/v1/SFM/1/Uplinks", methods=("GET", "POST", "PUT", "DELETE",))
Downlinks = Endpoint(path="/redfish/v1/SFM/1/Downlinks", methods=("GET", "POST", "PUT", "DELETE",))
Networks = Endpoint(path="/redfish/v1/SFM/1/Networks", methods=("GET", "POST", "PUT", "DELETE",))
RoutePolicy = Endpoint(path="/redfish/v1/SFM/1/RoutePolicy", methods=("GET", "POST", "PUT", "DELETE",))
NodeRoutePolicy = Endpoint(path="/redfish/v1/SFM/1/NodeRoutePolicy", methods=("GET", "POST", "PUT", "DELETE",))
Tenants = Endpoint(path="/redfish/v1/SFM/1/Tenants", methods=("GET", "POST", "PUT", "DELETE",))
Lag = Endpoint(path="/redfish/v1/SFM/1/Lag", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresTenantNodeLoopbackIP = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/TenantNodeLoopbackIP", methods=("GET", "POST", "PUT", "DELETE",))
TenantNodeLoopbackIP = Endpoint(path="/redfish/v1/SFM/1/TenantNodeLoopbackIP", methods=("GET", "POST", "PUT", "DELETE",))
PortGroup = Endpoint(path="/redfish/v1/SFM/1/PortGroup", methods=("GET", "POST", "PUT", "DELETE",))
PortBreakout = Endpoint(path="/redfish/v1/SFM/1/PortBreakout", methods=("GET", "POST", "PUT", "DELETE",))
PortChannel = Endpoint(path="/redfish/v1/SFM/1/PortChannel", methods=("GET", "POST", "PUT", "DELETE",))
OnboardingInstance = Endpoint(path="/redfish/v1/SFM/1/Onboarding/Instance", methods=("GET", "POST", "PUT", "DELETE",))
ProfileDevice = Endpoint(path="/redfish/v1/SFM/1/Profile/Device", methods=("GET", "POST", "PUT", "DELETE",))
Clusters = Endpoint(path="/redfish/v1/SFM/1/Clusters", methods=("GET", "POST", "PUT", "DELETE",))
DiscoveredDeviceInterfaces = Endpoint(path="/redfish/v1/SFM/1/DiscoveredDeviceInterfaces", methods=("GET", "POST", "PUT", "DELETE",))
DiscoverNode = Endpoint(path="/redfish/v1/SFM/1/DiscoverNode", methods=("GET", "POST", "PUT", "DELETE",))
DiscoveryRequest = Endpoint(path="/redfish/v1/SFM/1/DiscoveryRequest", methods=("GET", "POST", "DELETE",))
ExternalDeviceManagers = Endpoint(path="/redfish/v1/SFM/1/ExternalDeviceManagers", methods=("GET", "POST", "PUT", "DELETE",))
ExternalDeviceManagersUpdateInventory = Endpoint(path="/redfish/v1/SFM/1/ExternalDeviceManagers/UpdateInventory", methods=("POST",))
ClustersNics = Endpoint(path="/redfish/v1/SFM/1/Clusters/Nics", methods=("GET", "POST", "PUT", "DELETE",))
ClustersBonds = Endpoint(path="/redfish/v1/SFM/1/Clusters/Bonds", methods=("GET", "POST", "PUT", "DELETE",))
ClustersDefaultUplinks = Endpoint(path="/redfish/v1/SFM/1/Clusters/DefaultUplinks", methods=("GET", "POST", "PUT", "DELETE",))
InventoryDevices = Endpoint(path="/redfish/v1/SFM/1/InventoryDevices", methods=("GET", "POST", "PUT", "DELETE",))
InventoryDevicesNics = Endpoint(path="/redfish/v1/SFM/1/InventoryDevices/Nics", methods=("GET", "POST", "PUT", "DELETE",))
InventoryDevicesGpus = Endpoint(path="/redfish/v1/SFM/1/InventoryDevices/Gpus", methods=("GET",))
InventoryDevicesNicToGpuMappings = Endpoint(path="/redfish/v1/SFM/1/InventoryDevices/NicToGpuMappings", methods=("GET",))
InventoryUriResolver = Endpoint(path="/redfish/v1/SFM/1/InventoryUriResolver", methods=("POST",))
NodeInterfaceRemoteMacToDeviceMappings = Endpoint(path="/redfish/v1/SFM/1/NodeInterfaceRemoteMacToDeviceMappings", methods=("GET",))
DeviceModelTemplates = Endpoint(path="/redfish/v1/SFM/1/DeviceModelTemplates", methods=("GET", "POST", "DELETE",))
DeviceConnectivityValidations = Endpoint(path="/redfish/v1/SFM/1/DeviceConnectivityValidations", methods=("GET",))
DeviceConnectivityValidationsExport = Endpoint(path="/redfish/v1/SFM/1/DeviceConnectivityValidations/Export", methods=("POST",))
DiscoveredDevicesSummary = Endpoint(path="/redfish/v1/SFM/1/DiscoveredDevicesSummary", methods=("GET",))
InventoryClusterDevicesMap = Endpoint(path="/redfish/v1/SFM/1/InventoryClusterDevicesMap", methods=("GET", "POST", "PUT", "DELETE",))
ClustersDevices = Endpoint(path="/redfish/v1/SFM/1/Clusters/Devices", methods=("GET", "POST", "PUT", "DELETE",))
FabricsClusters = Endpoint(path="/redfish/v1/SFM/1/Fabrics/Clusters", methods=("GET",))
ClustersDevicesNics = Endpoint(path="/redfish/v1/SFM/1/Clusters/Devices/Nics", methods=("GET", "POST", "PUT", "DELETE",))
ClustersDevicesBonds = Endpoint(path="/redfish/v1/SFM/1/Clusters/Devices/Bonds", methods=("GET", "POST", "PUT", "DELETE",))
ClustersDeviceInterfaces = Endpoint(path="/redfish/v1/SFM/1/Clusters/DeviceInterfaces", methods=("GET", "POST", "PUT", "DELETE",))
ExternalDiscoveredNetworks = Endpoint(path="/redfish/v1/SFM/1/ExternalDiscoveredNetworks", methods=("GET", "POST", "PUT", "DELETE",))
ExternalDiscoveredAttachments = Endpoint(path="/redfish/v1/SFM/1/ExternalDiscoveredAttachments", methods=("GET", "POST", "PUT", "DELETE",))
ClustersDeviceInterfacesDiscNetworks = Endpoint(path="/redfish/v1/SFM/1/Clusters/DeviceInterfaces/DiscNetworks", methods=("GET", "POST", "PUT", "DELETE",))
ClustersDevicesNicsDiscNetworks = Endpoint(path="/redfish/v1/SFM/1/Clusters/Devices/Nics/DiscNetworks", methods=("GET", "POST", "PUT", "DELETE",))
ClustersHealthRecords = Endpoint(path="/redfish/v1/SFM/1/Clusters/HealthRecords", methods=("GET", "POST", "PUT", "DELETE",))
ClustersHealthStatus = Endpoint(path="/redfish/v1/SFM/1/Clusters/HealthStatus", methods=("GET",))
FabricsUplinks = Endpoint(path="/redfish/v1/SFM/1/Fabrics/Uplinks", methods=("GET",))
FabricsDownlinks = Endpoint(path="/redfish/v1/SFM/1/Fabrics/Downlinks", methods=("GET",))
ClustersApplyNetwork = Endpoint(path="/redfish/v1/SFM/1/Clusters/ApplyNetwork", methods=("POST", "PUT", "DELETE",))
ClustersDeploy = Endpoint(path="/redfish/v1/SFM/1/Clusters/Deploy", methods=("POST", "PUT", "DELETE",))
ClustersDeviceInterfacesApplyNetwork = Endpoint(path="/redfish/v1/SFM/1/Clusters/DeviceInterfaces/ApplyNetwork", methods=("POST", "PUT", "DELETE",))
ClustersDevicesNicsApplyNetwork = Endpoint(path="/redfish/v1/SFM/1/Clusters/Devices/Nics/ApplyNetwork", methods=("POST", "PUT", "DELETE",))
ClustersTrackedAttachmentApply = Endpoint(path="/redfish/v1/SFM/1/Clusters/TrackedAttachmentApply", methods=("GET", "POST", "PUT", "DELETE",))
ClustersReset = Endpoint(path="/redfish/v1/SFM/1/Clusters/Reset", methods=("POST", "PUT", "DELETE",))
ClustersValidatePreDeploy = Endpoint(path="/redfish/v1/SFM/1/Clusters/ValidatePreDeploy", methods=("POST", "PUT", "DELETE",))
Users = Endpoint(path="/redfish/v1/SFM/1/Users", methods=("GET", "POST", "PUT", "DELETE",))
UsersRoles = Endpoint(path="/redfish/v1/SFM/1/Users/Roles", methods=("GET", "POST", "PUT", "DELETE",))
Roles = Endpoint(path="/redfish/v1/SFM/1/Roles", methods=("GET", "POST", "PUT", "DELETE",))
UsersBulkDelete = Endpoint(path="/redfish/v1/SFM/1/Users/BulkDelete", methods=("POST", "PUT", "DELETE",))
UsersAssignRoles = Endpoint(path="/redfish/v1/SFM/1/Users/AssignRoles", methods=("POST", "PUT", "DELETE",))
UsersUnassignRoles = Endpoint(path="/redfish/v1/SFM/1/Users/UnassignRoles", methods=("POST", "PUT", "DELETE",))
ObservabilityNodeTenantTable = Endpoint(path="/redfish/v1/SFM/1/Observability/NodeTenantTable", methods=("GET",))
ObservabilityArpInfoTable = Endpoint(path="/redfish/v1/SFM/1/Observability/ArpInfoTable", methods=("GET",))
ObservabilityNodeRouteTable = Endpoint(path="/redfish/v1/SFM/1/Observability/NodeRouteTable", methods=("GET",))
ObservabilityBgpNeighbors = Endpoint(path="/redfish/v1/SFM/1/Observability/BgpNeighbors", methods=("GET",))
ObservabilityBgpL2vpnEvpnEadRoutes = Endpoint(path="/redfish/v1/SFM/1/Observability/BgpL2vpnEvpnEadRoutes", methods=("GET",))
ObservabilityBgpL2vpnEvpnEsRoutes = Endpoint(path="/redfish/v1/SFM/1/Observability/BgpL2vpnEvpnEsRoutes", methods=("GET",))
ObservabilityMacInfoTable = Endpoint(path="/redfish/v1/SFM/1/Observability/MacInfoTable", methods=("GET",))
ObservabilityFlowPathTable = Endpoint(path="/redfish/v1/SFM/1/Observability/FlowPathTable", methods=("GET",))
ObservabilityFlowPathTableFlowPathKeys = Endpoint(path="/redfish/v1/SFM/1/Observability/FlowPathTable/FlowPathKeys", methods=("GET",))
ObservabilitySettings = Endpoint(path="/redfish/v1/SFM/1/Observability/Settings", methods=("GET", "PUT",))
ObservabilitySettingsResetDefaults = Endpoint(path="/redfish/v1/SFM/1/Observability/Settings/ResetDefaults", methods=("POST",))
ObservabilityRemoteWrite = Endpoint(path="/redfish/v1/SFM/1/Observability/RemoteWrite", methods=("GET", "POST", "PUT", "DELETE",))
ObservabilityRemoteWriteCertificateImport = Endpoint(path="/redfish/v1/SFM/1/Observability/RemoteWrite/CertificateImport", methods=("GET", "POST", "PUT", "DELETE",))
ObservabilityRemoteWriteCertificateImportServerCertificate = Endpoint(path="/redfish/v1/SFM/1/Observability/RemoteWrite/CertificateImport/ServerCertificate", methods=("GET", "POST", "PUT", "DELETE",))
ObservabilityRemoteWriteCertificateImportClientCertificate = Endpoint(path="/redfish/v1/SFM/1/Observability/RemoteWrite/CertificateImport/ClientCertificate", methods=("GET", "POST", "PUT", "DELETE",))
ObservabilityRemoteWriteCertificateImportClientKey = Endpoint(path="/redfish/v1/SFM/1/Observability/RemoteWrite/CertificateImport/ClientKey", methods=("GET", "POST", "PUT", "DELETE",))
ObservabilityHeatmap = Endpoint(path="/redfish/v1/SFM/1/Observability/Heatmap", methods=("GET", "PUT",))
ObservabilityHeatmapRules = Endpoint(path="/redfish/v1/SFM/1/Observability/Heatmap/Rules", methods=("GET", "PUT",))
Backups = Endpoint(path="/redfish/v1/SFM/1/Backups", methods=("GET", "POST", "PUT", "DELETE", "PATCH",))
BackupsDownload = Endpoint(path="/redfish/v1/SFM/1/Backups/Download", methods=("POST",))
BackupsExport = Endpoint(path="/redfish/v1/SFM/1/Backups/Export", methods=("POST",))
BackupsExportReqStatus = Endpoint(path="/redfish/v1/SFM/1/Backups/ExportReqStatus", methods=("GET",))
AutoBackupConfig = Endpoint(path="/redfish/v1/SFM/1/AutoBackupConfig", methods=("GET", "PUT",))
BackupRolloverConfig = Endpoint(path="/redfish/v1/SFM/1/BackupRolloverConfig", methods=("GET", "PUT",))
Restores = Endpoint(path="/redfish/v1/SFM/1/Restores", methods=("GET", "POST", "PUT", "DELETE",))
RestoresImport = Endpoint(path="/redfish/v1/SFM/1/Restores/Import", methods=("POST",))
LCOperationStatus = Endpoint(path="/redfish/v1/SFM/1/LCOperationStatus", methods=("GET",))
NodeUpgrade = Endpoint(path="/redfish/v1/SFM/1/NodeUpgrade", methods=("GET", "POST", "PUT", "DELETE",))
NodeUpgradeStatus = Endpoint(path="/redfish/v1/SFM/1/NodeUpgradeStatus", methods=("GET", "POST", "PUT", "DELETE",))
NodeUpgradeRetry = Endpoint(path="/redfish/v1/SFM/1/NodeUpgrade/Retry", methods=("POST",))
SfmUpgrade = Endpoint(path="/redfish/v1/SFM/1/SfmUpgrade", methods=("GET", "POST", "PUT", "DELETE",))
SwitchSupportedVersions = Endpoint(path="/redfish/v1/SFM/1/SwitchSupportedVersions", methods=("GET",))
Infrastructures = Endpoint(path="/redfish/v1/SFM/1/Infrastructures", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructureEntities = Endpoint(path="/redfish/v1/SFM/1/InfrastructureEntities", methods=("PUT", "PATCH",))
InfrastructuresNodes = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Nodes", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresNodeRoutePolicy = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/NodeRoutePolicy", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresRoutePolicy = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/RoutePolicy", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresInterfaces = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Interfaces", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresPortGroups = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/PortGroups", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresSnmpViews = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/SnmpViews", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresSnmpGroups = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/SnmpGroups", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresSnmpUsers = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/SnmpUsers", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresSnmpHosts = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/SnmpHosts", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresBreakouts = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Breakouts", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresFabrics = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Fabrics", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresLags = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Lags", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresPredeployments = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Predeployments", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresTenants = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Tenants", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresNetworks = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Networks", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresUplinks = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Uplinks", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresDownlinks = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Downlinks", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresAAA = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/AAA", methods=("GET", "PUT",))
InfrastructuresLdap = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Ldap", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresRadiusServers = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/RadiusServers", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresDot1xDynamicObjects = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Dot1xDynamicObjects", methods=("GET", "POST", "PUT",))
InfrastructuresClusterDevices = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ClusterDevices", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresClusterProfiles = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ClusterProfiles", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresInventoryDevices = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/InventoryDevices", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresExternalDeviceManagers = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ExternalDeviceManagers", methods=("GET", "POST", "DELETE",))
InfrastructuresStatus = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Status", methods=("GET",))
InfrastructuresAction = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Action", methods=("POST",))
InfrastructuresPods = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Pods", methods=("POST", "DELETE",))
InfrastructuresRacks = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Racks", methods=("POST", "DELETE",))
InfrastructuresSpines = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Spines", methods=("POST", "DELETE",))
InfrastructuresBorderLeafRacks = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/BorderLeafRacks", methods=("POST", "DELETE",))
InfrastructuresSuperSpines = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/SuperSpines", methods=("POST", "DELETE",))
InfrastructuresImportAllAndUpdate = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ImportAllAndUpdate", methods=("POST",))
InfrastructuresExportAll = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ExportAll", methods=("POST",))
InfrastructuresSwitchesExport = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Switches/Export", methods=("POST",))
InfrastructuresResourcesExport = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Resources/Export", methods=("POST",))
InfrastructuresDevicesExport = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Devices/Export", methods=("POST",))
InfrastructuresExternalDeviceManagersExport = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ExternalDeviceManagers/Export", methods=("POST",))
InfrastructuresSwitchesImport = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Switches/Import", methods=("POST",))
InfrastructuresResourcesImport = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Resources/Import", methods=("POST",))
InfrastructuresDevicesImport = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/Devices/Import", methods=("POST",))
InfrastructuresExternalDeviceManagersImport = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ExternalDeviceManagers/Import", methods=("POST",))
InfrastructuresFabricManagements = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/FabricManagements", methods=("GET", "POST", "PUT", "DELETE",))
ExternalDeviceManagersIdracs = Endpoint(path="/redfish/v1/SFM/1/ExternalDeviceManagers/Idracs", methods=("GET", "POST", "PUT", "DELETE",))
FabricsDscpToPrioMapTable = Endpoint(path="/redfish/v1/SFM/1/Fabrics/DscpToPrioMapTable", methods=("GET", "PUT",))
FabricsSchedulerPolicy = Endpoint(path="/redfish/v1/SFM/1/Fabrics/SchedulerPolicy", methods=("GET", "PUT",))
FabricsWredEcnProfile = Endpoint(path="/redfish/v1/SFM/1/Fabrics/WredEcnProfile", methods=("GET", "PUT",))
FabricsSpineGroupWredEcnProfile = Endpoint(path="/redfish/v1/SFM/1/Fabrics/SpineGroupWredEcnProfile", methods=("GET", "POST", "PUT", "DELETE",))
EsiSwitch = Endpoint(path="/redfish/v1/SFM/1/EsiSwitch", methods=("GET",))
InfrastructuresFixedISLs = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/FixedISLs", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresRangedISLs = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/RangedISLs", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresFixedISLsActionReplaceNodeISLs = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/FixedISLs/ActionReplaceNodeISLs", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresRangedISLsActionReplaceNodeISLs = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/RangedISLs/ActionReplaceNodeISLs", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresISLConnectionsValidationStatus = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ISLConnectionsValidationStatus", methods=("GET",))
InfrastructuresISLConnectionsValidationErrors = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ISLConnectionsValidationErrors", methods=("GET",))
InfrastructuresTopologyGraph = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/TopologyGraph", methods=("GET",))
InfrastructuresPingMesh = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/PingMesh", methods=("GET", "POST",))
InfrastructuresSourceInterfaces = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/SourceInterfaces", methods=("GET", "POST", "DELETE",))
InfrastructuresOSPFPolicies = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/OSPFPolicies", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresIPPrefixLists = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/IPPrefixLists", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresRouteMaps = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/RouteMaps", methods=("GET", "POST", "PUT", "DELETE",))
InfrastructuresOSPFAttachments = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/OSPFAttachments", methods=("GET", "POST", "PUT", "DELETE",))
ZtpSwitch = Endpoint(path="/redfish/v1/SFM/1/ZtpSwitch", methods=("GET",))
ZtpGlobal = Endpoint(path="/redfish/v1/SFM/1/ZtpGlobal", methods=("GET",))
ZtpPool = Endpoint(path="/redfish/v1/SFM/1/ZtpPool", methods=("GET",))
SfmInterfaces = Endpoint(path="/redfish/v1/SFM/1/SfmInterfaces", methods=("GET",))
InfrastructuresICLConnectionsValidationStatus = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ICLConnectionsValidationStatus", methods=("GET",))
InfrastructuresICLConnectionsValidationErrors = Endpoint(path="/redfish/v1/SFM/1/Infrastructures/ICLConnectionsValidationErrors", methods=("GET", "PUT",))
UploadEnterpriseImage = Endpoint(path="/redfish/v1/SFM/1/UploadEnterpriseImage", methods=("GET", "POST",))
UploadLiteImage = Endpoint(path="/redfish/v1/SFM/1/UploadLiteImage", methods=("GET", "POST",))
UploadLiteSignatureFile = Endpoint(path="/redfish/v1/SFM/1/UploadLiteSignatureFile", methods=("POST",))
UploadEnterpriseSignatureFile = Endpoint(path="/redfish/v1/SFM/1/UploadEnterpriseSignatureFile", methods=("POST",))
AIFactoryInfrastructure = Endpoint(path="/redfish/v1/SFM/1/AIFactoryInfrastructure", methods=("POST",))
GenerateAITemplateSummary = Endpoint(path="/redfish/v1/SFM/1/GenerateAITemplateSummary", methods=("POST",))
UploadEnterpriseImage_1 = Endpoint(path="/redfish/v1/SFM/1/UploadEnterpriseImage", methods=("GET", "POST",))
UploadLiteImage_1 = Endpoint(path="/redfish/v1/SFM/1/UploadLiteImage", methods=("GET", "POST",))
UploadLiteSignatureFile_1 = Endpoint(path="/redfish/v1/SFM/1/UploadLiteSignatureFile", methods=("POST",))
UploadEnterpriseSignatureFile_1 = Endpoint(path="/redfish/v1/SFM/1/UploadEnterpriseSignatureFile", methods=("POST",))
AIFactoryInfrastructure_1 = Endpoint(path="/redfish/v1/SFM/1/AIFactoryInfrastructure", methods=("POST",))
GenerateAITemplateSummary_1 = Endpoint(path="/redfish/v1/SFM/1/GenerateAITemplateSummary", methods=("POST",))
SwitchBackups = Endpoint(path="/redfish/v1/SFM/1/SwitchBackups", methods=("GET", "POST", "DELETE", "PATCH",))
SwitchBackupsDownload = Endpoint(path="/redfish/v1/SFM/1/SwitchBackups/Download", methods=("POST",))
SwitchBackupsExport = Endpoint(path="/redfish/v1/SFM/1/SwitchBackups/Export", methods=("POST",))
SwitchBackupsExportReqStatus = Endpoint(path="/redfish/v1/SFM/1/SwitchBackups/ExportReqStatus", methods=("GET",))
SwitchBackupsMarkGoldenByFilter = Endpoint(path="/redfish/v1/SFM/1/SwitchBackups/MarkGoldenByFilter", methods=("POST",))
SwitchBackupsUnMarkGolden = Endpoint(path="/redfish/v1/SFM/1/SwitchBackups/UnMarkGolden", methods=("POST",))
SwitchBackupsConfigDrift = Endpoint(path="/redfish/v1/SFM/1/SwitchBackups/ConfigDrift", methods=("POST",))
SwitchBackupsExportGolden = Endpoint(path="/redfish/v1/SFM/1/SwitchBackups/ExportGolden", methods=("POST",))
