"""Scaffold a new workspace directory."""

from __future__ import annotations

from pathlib import Path

_CONFIG_TEMPLATE = """\
apiVersion: restful/v1
workspace:
  name: {name}

apis: []
  # - name: my-api
  #   alias: api
  #   plugin: snf-instance-rest
  #   source: rbac_access_matrix.json
  #   auth:
  #     type: bearer
  #     login_path: /security/v1/auth/login
  #     username: admin
  #     password_env: MY_PASSWORD
"""

_MAIN_TEMPLATE = """\
\"\"\"Workspace entry point. Auto-generated by restful.\"\"\"
import sys
from pathlib import Path

# Add workspace root to sys.path so 'from apis.x import endpoints' works
sys.path.insert(0, str(Path(__file__).parent))
"""

_GITIGNORE_TEMPLATE = """\
.restful/
__pycache__/
*.pyc
"""


def create_workspace(name: str, parent: Path | None = None) -> Path:
    """Create a workspace directory with config, __main__.py, and subdirectories."""
    name_path = Path(name)
    if name_path.is_absolute():
        root = name_path
    else:
        root = (parent or Path.cwd()) / name

    # Use just the directory name for the config file, not the full path
    dir_name = root.name

    if root.exists():
        raise FileExistsError(f"Directory already exists: {root}")

    root.mkdir(parents=True)

    # Config file
    config_path = root / f"{dir_name}.config.yaml"
    config_path.write_text(_CONFIG_TEMPLATE.format(name=dir_name), encoding="utf-8")

    # Entry point
    main_path = root / "__main__.py"
    main_path.write_text(_MAIN_TEMPLATE, encoding="utf-8")

    # Directories
    (root / "apis").mkdir()
    (root / "apis" / "__init__.py").write_text("", encoding="utf-8")
    (root / "notebooks").mkdir()
    (root / ".restful").mkdir()

    # Gitignore
    (root / ".gitignore").write_text(_GITIGNORE_TEMPLATE, encoding="utf-8")

    return root
