"""
Basic REST client usage — no workspace, no workflows.

Shows how to use the Client directly for quick API calls.
"""

from restful import Client
from restful.models import Endpoint

# ── Define endpoints as typed constants ──────────────────────────────────
# These would normally be auto-generated by a plugin, but you can define them manually.

Users = Endpoint(path="/api/v1/users", methods=("GET", "POST"))
UserById = Endpoint(path="/api/v1/users", methods=("GET", "PUT", "DELETE"))
Posts = Endpoint(path="/api/v1/posts", methods=("GET", "POST"))

# ── Create a client ──────────────────────────────────────────────────────

# Simple client (no auth)
client = Client(base_url="https://jsonplaceholder.typicode.com")

# With bearer auth (auto-caches tokens, retries on 401)
# auth_client = Client(
#     base_url="https://api.example.com",
#     auth=BearerAuth(
#         base_url="https://api.example.com",
#         login_path="/auth/login",
#         payload={"username": "admin", "password": "secret"},
#     ),
# )

# ── Make requests ────────────────────────────────────────────────────────

# GET all users
response = client.get(Users)
print(f"Users: {response.status_code}")
users = response.json()
print(f"  Found {len(users)} users")
print(f"  First: {users[0]['name']}")

# GET with OData key predicates: /users(1)
response = client.get(UserById, params={"id": "1"})
print(f"\nUser 1: {response.json()['name']}")

# GET with query parameters: /posts?userId=1
response = client.get(Posts, query={"userId": 1})
posts = response.json()
print(f"\nPosts by user 1: {len(posts)} posts")

# POST (create)
response = client.post(
    Posts,
    payload={"title": "My Post", "body": "Hello world", "userId": 1},
    expected_status={200, 201},
)
print(f"\nCreated post: {response.status_code}")
print(f"  ID: {response.json().get('id')}")
